ui: tape
browsers:
  - name: chrome
    version: latest
    platform: Linux
  - name: ie
    version: 9..latest
  - name: iphone
    version: "4.3..latest"
  - name: firefox
    version: latest
    platform: Linux
  - name: ipad
    version: "4.3..latest"
  - name: safari
    version: 5..latest
  - name: android
    version: "4.0..latest"
